project:
  type: website
  output-dir: _site

website:
  title: "abc-ds"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Codebook
        href: codebook.qmd
      - text: Documentation
        href: https://abcds-core.github.io/documentation/

format:
  html:
    theme:
      - lumen
    css: styles.css
    include-in-header:
      text: |
        <link href="https://unpkg.com/tabulator-tables@6.3.0/dist/css/tabulator.min.css" rel="stylesheet">
        <script src="https://unpkg.com/tabulator-tables@6.3.0/dist/js/tabulator.min.js"></script>

execute:
  freeze: auto

resources:
  - codebook.json
