export const ACKNOWLEDGEMENTS = `
The Alzheimer’s Biomarkers Consortium–Down Syndrome (ABC-DS) is funded by the National Institute on Aging and the National Institute for Child Health and Human Development (U01 AG051406, U01 AG051412, U19 AG068054) and the Investigation of Co-occurring conditions across the Lifespan to Understand Down syndrome (NIH INCLUDE Project). The work contained in this publication was also supported through the following National Institutes of Health Programs: The Alzheimer’s Disease Research Centers Program (P50 AG008702, P30 AG062421, P50 AG016573, P50 AG005133, P50 AG005681, P30 AG062715, P30 AG066519, P30 AG066468 and P30 AG072973), the Eunice Kennedy Shriver Intellectual and Developmental Disabilities Research Centers Program (P50 HD105353), the National Center for Advancing Translational Sciences (UL1 TR001873, UL1 TR002373, UL1 TR001414, UL1 TR001857, UL1 TR002345, UL1 TR002366), the National Centralized Repository for Alzheimer Disease and Related Dementias (U24 AG021886), and DS-Connect® (The Down Syndrome Registry) supported by the Eunice Kennedy Shriver National Institute of Child Health and Human Development (NICHD). In Cambridge, UK this research was supported by the NIHR Cambridge Biomedical Research Centre and the Windsor Research Unit, CPFT, Fulbourn Hospital Cambridge, UK.

The authors are grateful to the ABC-DS study participants, their families and care providers, and the ABC-DS research and support staff for their contributions to this study. This manuscript has been reviewed by ABC-DS investigators for scientific content and consistency of data interpretation with previous ABC-DS study publications. The content is solely the responsibility of the authors and does not necessarily represent the official views of the NIH, the CPFT, the NIHR or the UK Department of Health and Social Care

*Alzheimer’s Biomarker Consortium- Down Syndrome (ABC-DS) Investigators:	

Beau M. Ances, MD PhD; Howard F. Andrews, PhD; Karen Bell, MD; Adam M. Brickman, PhD; Stephanie Brown, PhD; Peter Bulova, MD; Jeff Burns, MD; Amrita Cheema, PhD; Bradley T. Christian, PhD; Isabel Clare, PhD; Ann D. Cohen, PhD; Eric W. Doran, MS; Tatiana M. Foroud, PhD; Benjamin L. Handen, PhD; Jordan Harp, PhD; Sigan L. Hartley, PhD; Elizabeth Head, PhD; Christy Hom, PhD; Milos D. Ikonomovic, MD; Sterling C Johnson, PhD; M. Ilyas Kamboh, PhD; David Keator, PhD; Julia K. Kofler, MD; Sharon J. Krinsky-McHale, PhD; Florence Lai, MD; Patrick Lao, PhD; Charles Laymon, PhD; Joseph Hyungwoo Lee, PhD; Ira T. Lott, MD; Mark Mapstone, PhD; Sid O’Bryant, PhD; Deborah Pang, MPH; Melissa Petersen, PhD; Julie C. Price, PhD; Lauren Ptomey, PhD; Margaret Pulsifer, PhD; Michael S. Rafii, MD PhD; Herminia Diana Rosas, MD; Carol Salas, PsyD; Frederick Schmitt, PhD; Nicole Schupf, PhD; Wayne P. Silverman, PhD; Dana L. Tudorascu, PhD; Badri Varadarajan, PhD; Michael A. Yassa, PhD; Shahid Zaman, MD PhD; Fan Zhang, PhD
`;
